//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string CarNo { get; set; }
        public string CarName { get; set; }
        public short CarType { get; set; }
        public int Capacity { get; set; }
        public int OwnerId { get; set; }
        public int Id { get; set; }
        public Nullable<int> User_UserId { get; set; }
    }
}
