//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarPoolDBContext : DbContext
    {
        public CarPoolDBContext()
            : base("name=CarPoolDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PriceLimit> PriceLimits { get; set; }
        public virtual DbSet<Ride> Rides { get; set; }
        public virtual DbSet<RouteInformation> RouteInformations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
