//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        public int RideId { get; set; }
        public int NoOfSeatsAvailable { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string CarNumber { get; set; }
        public int RideProviderId { get; set; }
        public decimal PricePerKilometer { get; set; }
        public System.DateTime DateOfRide { get; set; }
        public string ViaPlaces { get; set; }
        public Nullable<int> User_UserId { get; set; }
        public Nullable<int> Car_Id { get; set; }
    }
}
