//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteInformation
    {
        public int Id { get; set; }
        public int Source { get; set; }
        public int Destination { get; set; }
        public int Distance { get; set; }
        public int Duration { get; set; }
    }
}
