// <auto-generated />
namespace CarPool.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class version2Migrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version2Migrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202002050911500_version2Migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
